import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join, relative, sep } from "node:path";
import { createHash } from "node:crypto";
import { contentTypeFor } from "../apps/runner/src/ui-serve.ts";

export const COMPILE_TARGETS = [
  { target: "bun-darwin-arm64", outfile: "purser-darwin-arm64" },
  { target: "bun-darwin-x64", outfile: "purser-darwin-x64" },
  { target: "bun-linux-x64", outfile: "purser-linux-x64" },
  { target: "bun-windows-x64", outfile: "purser-windows-x64.exe" },
] as const;

export type CompileTarget = (typeof COMPILE_TARGETS)[number]["target"];

const EMPTY_EMBED = `/** Generated by \`bun run compile\`. The stub is empty so typecheck does not need a Vite dist. */
export const EMBEDDED_UI: { path: string; contentType: string; bodyBase64: string }[] = [];
`;

function repoRoot(): string {
  return join(import.meta.dir, "..");
}

export async function buildWebUi(root: string): Promise<string> {
  const proc = Bun.spawn(["bun", "run", "build"], {
    cwd: join(root, "apps/web"),
    stdout: "inherit",
    stderr: "inherit",
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error("vite build failed");
  }
  const dist = join(root, "apps/web/dist");
  if (!existsSync(join(dist, "index.html"))) {
    throw new Error("apps/web/dist/index.html missing after build");
  }
  return dist;
}

export function stageUi(root: string, dist: string): string {
  const ui = join(root, "apps/runner/ui");
  rmSync(ui, { recursive: true, force: true });
  mkdirSync(ui, { recursive: true });
  cpSync(dist, ui, { recursive: true });
  return ui;
}

function walkFiles(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const abs = join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkFiles(abs));
      continue;
    }
    if (entry.isFile()) {
      out.push(abs);
    }
  }
  return out;
}

/** Bun 1.3.14 has no `--asset` directory flag. Import the UI as a TS module instead. */
export function writeEmbeddedUiModule(root: string, uiDir: string): string {
  const genPath = join(root, "apps/runner/src/embedded-ui.gen.ts");
  const files = walkFiles(uiDir).sort();
  const rows = files.map((abs) => {
    const rel = relative(uiDir, abs).split(sep).join("/");
    const bodyBase64 = readFileSync(abs).toString("base64");
    return `  { path: ${JSON.stringify(rel)}, contentType: ${JSON.stringify(contentTypeFor(rel))}, bodyBase64: ${JSON.stringify(bodyBase64)} }`;
  });
  const body = `/** Generated by \`bun run compile\`. Do not edit. */
export const EMBEDDED_UI: { path: string; contentType: string; bodyBase64: string }[] = [
${rows.join(",\n")}
];
`;
  writeFileSync(genPath, body);
  return genPath;
}

export function restoreEmbeddedUiStub(root: string): void {
  writeFileSync(join(root, "apps/runner/src/embedded-ui.gen.ts"), EMPTY_EMBED);
}

export async function compileOne(input: {
  root: string;
  target: CompileTarget;
  outfileName: string;
}): Promise<string> {
  const outDir = join(input.root, "dist/bin");
  mkdirSync(outDir, { recursive: true });
  const outfile = join(outDir, input.outfileName);
  const args = ["build", "--compile", `--target=${input.target}`, "--outfile", outfile, "./src/index.ts"];
  if (input.target.startsWith("bun-windows-")) {
    args.push("--windows-hide-console");
  }
  const proc = Bun.spawn(["bun", ...args], {
    cwd: join(input.root, "apps/runner"),
    stdout: "inherit",
    stderr: "inherit",
  });
  const code = await proc.exited;
  if (code !== 0) {
    throw new Error(`compile failed for ${input.target}`);
  }
  return outfile;
}

export function sha256File(path: string): string {
  return createHash("sha256").update(readFileSync(path)).digest("hex");
}

async function main(): Promise<void> {
  const root = repoRoot();
  const all = process.argv.includes("--all");
  const dist = await buildWebUi(root);
  const uiDir = stageUi(root, dist);
  writeEmbeddedUiModule(root, uiDir);
  try {
    const wanted = all
      ? COMPILE_TARGETS
      : COMPILE_TARGETS.filter((row) => {
          if (process.platform === "linux" && process.arch === "x64") {
            return row.target === "bun-linux-x64";
          }
          if (process.platform === "darwin" && process.arch === "arm64") {
            return row.target === "bun-darwin-arm64";
          }
          if (process.platform === "darwin" && process.arch === "x64") {
            return row.target === "bun-darwin-x64";
          }
          if (process.platform === "win32") {
            return row.target === "bun-windows-x64";
          }
          return row.target === "bun-linux-x64";
        });
    const lines: string[] = [];
    for (const row of wanted) {
      const path = await compileOne({ root, target: row.target, outfileName: row.outfile });
      lines.push(`${sha256File(path)}  ${row.outfile}`);
      console.log(`compiled ${path}`);
    }
    if (wanted.length === 1) {
      const purserPath = join(root, "dist/bin/purser");
      rmSync(purserPath, { force: true });
      if (process.platform === "win32") {
        cpSync(join(root, "dist/bin", wanted[0]!.outfile), `${purserPath}.exe`);
      } else {
        symlinkSync(wanted[0]!.outfile, purserPath);
      }
      console.log(`linked dist/bin/purser → ${wanted[0]!.outfile}`);
    }
    await Bun.write(join(root, "dist/bin/SHA256SUMS"), `${lines.join("\n")}\n`);
  } finally {
    restoreEmbeddedUiStub(root);
  }
}

if (import.meta.main) {
  await main();
}
